name = "lemur-archive"
main = "cloudflare/src/worker.js"
compatibility_date = "2026-02-14"

[assets]
directory = "./Web"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "lemur-db"
database_id = "5b8f2fc6-c283-4e54-9360-8adca603518c"
